/**
 * Renders the {@link ItemData} as a list item.
 *
 * @param {DataType} itemData The {@link ItemData} used to render the list item.
 * @param {string} key The unique identifier generated by {@link ItemKeyGenerator}.
 * @param {number} index The index of the {@link ItemData}.
 * @returns Returns the corresponding {@link HTMLElement}.
 */
export type ItemRenderer<DataType> = (itemData: DataType, key: string, index: number) => HTMLElement;
